# tasks file for nisclient
---
# Tasks for nis/yp clients

- yum: name="{{ item }}" state=present
  with_items:
    - ypbind
    - rpcbind
    - libselinux-python

- selinux: state=disabled
>>>>>>> 9c9b3fb1fc1ccff5e8b7e73220ca8060010e0234

- name: set up authconfig to use NIS
  shell: '/sbin/authconfig --enablenis 
          --nisdomain="{{ nisdomain }}"
          --nisserver="{{ nismasterip }}"
          --update'
  notify:
    - enableypbind
    - enablerpcbind
    - startypbind
    - startrpcbind
