---
# handlers file for nisclient
#
- name: enableypbind
  service: name=ypbind enabled=yes

- name: startypbind
  service: name=ypbind state=started

- name: enablerpc
  service: name=rpcbind enabled=yes

- name: startrpcbind
  service: name=rpcbind state=started
