---
# handlers file for nisclient
#
- name: enableyp
  service: name=yp enabled=yes

- name: startyp
  service: name=yp state=started

- name: enablerpc
  service: name=rpc enabled=yes

- name: startrpc
  service: name=rpc state=started
